{
 "title": "BugBoard Operations & Performance Dashboard",
 "tags": [
  "bugboard",
  "fastapi",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[2m])) by (handler, status)",
     "legendFormat": "{{handler}} [{{status}}]"
    }
   ]
  },
  {
   "title": "P95 Request Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Application Error Rate (5xx / 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[2m])) or vector(0)",
     "legendFormat": "5xx Server Errors"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[2m])) or vector(0)",
     "legendFormat": "4xx Client Errors"
    }
   ]
  }
 ]
}