apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bugboard.fullname" . }}-config
  labels:
    {{- include "bugboard.labels" . | nindent 4 }}
data:
  UPLOAD_DIR: {{ .Values.backend.env.uploadDir | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.corsOrigins | quote }}
  BACKEND_URL: "http://{{ include "bugboard.fullname" . }}-backend:{{ .Values.backend.service.port }}"
